// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBHS.API.Models;

public partial class LeaveRequests
{
    public int Id { get; set; }

    public int UserDetailId { get; set; }

    public int LeaveTypeId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int LeaveStatusId { get; set; }

    public string Reason { get; set; }

    public decimal? Days { get; set; }

    public byte[] UploadDocument { get; set; }

    public string ApprovedByUserDetailId { get; set; }

    public DateTime? DateApproved { get; set; }

    public string RejectedByUserDetailId { get; set; }

    public DateTime? DateRejected { get; set; }

    public virtual LeaveStatus LeaveStatus { get; set; }

    public virtual LeaveTypes LeaveType { get; set; }

    public virtual UserDetails UserDetail { get; set; }
}