// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBHS.API.Models;

public partial class LeaveStatus
{
    public int Id { get; set; }

    public string LeaveStatusName { get; set; }

    public virtual ICollection<LeaveRequests> LeaveRequests { get; set; } = new List<LeaveRequests>();

    public virtual ICollection<OncallRequests> OncallRequests { get; set; } = new List<OncallRequests>();
}