// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBHS.API.Models;

public partial class OncallRequests
{
    public int Id { get; set; }

    public int UserDetailId { get; set; }

    public int DepartmentId { get; set; }

    public DateTime? DateTimeOnCall { get; set; }

    public string ApprovedByUserDetailId { get; set; }

    public DateTime? DateApproved { get; set; }

    public string RejectedByUserDetailId { get; set; }

    public DateTime? DateRejected { get; set; }

    public int LeaveStatusId { get; set; }

    public virtual Departments Department { get; set; }

    public virtual LeaveStatus LeaveStatus { get; set; }

    public virtual UserDetails UserDetail { get; set; }
}