// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBHS.API.Models;

public partial class ShiftTypes
{
    public int Id { get; set; }

    public string ShiftTypeName { get; set; }

    public virtual ICollection<ShiftDetails> ShiftDetails { get; set; } = new List<ShiftDetails>();
}