// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBHS.API.Models;

public partial class ShiftDetails
{
    public int Id { get; set; }

    public int UserDetailId { get; set; }

    public int ShiftTypeId { get; set; }

    public DateTime? Date { get; set; }

    public virtual ShiftTypes ShiftType { get; set; }

    public virtual UserDetails UserDetail { get; set; }
}