// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBHS.API.Models;

public partial class UserDetails
{
    public int Id { get; set; }

    public string AspNetUserId { get; set; }

    public int DepartmentId { get; set; }

    public int WorkTitleId { get; set; }

    public virtual Departments Department { get; set; }

    public virtual ICollection<LeaveRequests> LeaveRequests { get; set; } = new List<LeaveRequests>();

    public virtual ICollection<OncallRequests> OncallRequests { get; set; } = new List<OncallRequests>();

    public virtual ICollection<ShiftDetails> ShiftDetails { get; set; } = new List<ShiftDetails>();

    public virtual WorkTitles WorkTitle { get; set; }
}