// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SBHS.Models;

public partial class LeaveRequests
{
    public int Id { get; set; }

    [Display(Name = "Employees")]
    public int UserDetailId { get; set; }

    [Display(Name = "Leave Type")]
    public int LeaveTypeId { get; set; }

    [Display(Name = "Start Date")]
    public DateTime? StartDate { get; set; }

    [Display(Name = "End Date")]
    public DateTime? EndDate { get; set; }

    [Display(Name = "Status")]
    public int LeaveStatusId { get; set; }

    [Display(Name = "Reason")]
    public string Reason { get; set; }

    [Display(Name = "Days")]
    public decimal? Days { get; set; }

    [Display(Name = "Document")]
    public byte[] UploadDocument { get; set; }

    [Display(Name = "Approved By")]
    public string ApprovedByUserDetailId { get; set; }

    [Display(Name = "Date Approved")]
    public DateTime? DateApproved { get; set; }

    [Display(Name = "Rejected By")]
    public string RejectedByUserDetailId { get; set; }

    [Display(Name = "Rejected By")]
    public DateTime? DateRejected { get; set; }

    public virtual LeaveStatus LeaveStatus { get; set; }

    public virtual LeaveTypes LeaveType { get; set; }

    public virtual UserDetails UserDetail { get; set; }
}