// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBHS.Models;

public partial class LeaveConditions
{
    public int Id { get; set; }

    public string LeaveConditionName { get; set; }

    public int WorkTitleId { get; set; }

    public string MaxAmountofStaffAllowed { get; set; }

    public virtual WorkTitles WorkTitle { get; set; }
}