// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SBHS.Models;

public partial class ShiftDetails
{
    public int Id { get; set; }
    
    [Display(Name = "Employees")]
    public int UserDetailId { get; set; }
    
    [Display(Name = "Shift Type")]
    public int ShiftTypeId { get; set; }
    
    [Display(Name = "Date")]
    public DateTime? Date { get; set; }

    public virtual ShiftTypes ShiftType { get; set; }

    public virtual UserDetails UserDetail { get; set; }
}