// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SBHS.Models;

public partial class ShiftTypes
{
    public int Id { get; set; }

    [Display(Name = "Shift Type")]
    public string ShiftTypeName { get; set; }

    public virtual ICollection<ShiftDetails> ShiftDetails { get; set; } = new List<ShiftDetails>();
}