// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SBHS.Models;

public partial class UserDetails
{
    public int Id { get; set; }

    [Display(Name = "Employees")]
    public string AspNetUserId { get; set; }

    [Display(Name = "Department")]
    public int DepartmentId { get; set; }

    [Display(Name = "Work Title")]
    public int WorkTitleId { get; set; }

    [Display(Name = "Full Name")]
    public string FullName { get; set; }

    public virtual Departments Department { get; set; }

    public virtual ICollection<LeaveRequests> LeaveRequests { get; set; } = new List<LeaveRequests>();

    public virtual ICollection<OncallRequests> OncallRequests { get; set; } = new List<OncallRequests>();

    public virtual ICollection<ShiftDetails> ShiftDetails { get; set; } = new List<ShiftDetails>();

    public virtual WorkTitles WorkTitle { get; set; }
}