// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SBHS.Models;

public partial class WorkTitles
{
    public int Id { get; set; }

    [Display(Name = "Work Title")]
    public string WorkTitleName { get; set; }

    public virtual ICollection<LeaveConditions> LeaveConditions { get; set; } = new List<LeaveConditions>();

    public virtual ICollection<UserDetails> UserDetails { get; set; } = new List<UserDetails>();
}